const CITY_PROXY_TYPE_GOLD = 3
const CITY_PROXY_TYPE_SILVER = 2
const CITY_PROXY_TYPE_CU = 1

const CITY_PROXY_TYPE_GOLD_LABEL = '金牌代理'
const CITY_PROXY_TYPE_SILVER_LABEL = '银牌代理'
const CITY_PROXY_TYPE_CU_LABEL = '铜牌代理'

const CITY_PROXY_TYPE_MAP = {
  [CITY_PROXY_TYPE_GOLD]: CITY_PROXY_TYPE_GOLD_LABEL,
  [CITY_PROXY_TYPE_SILVER]: CITY_PROXY_TYPE_SILVER_LABEL,
  [CITY_PROXY_TYPE_CU]: CITY_PROXY_TYPE_CU_LABEL
}

export {
  CITY_PROXY_TYPE_GOLD,
  CITY_PROXY_TYPE_SILVER,
  CITY_PROXY_TYPE_CU,
  CITY_PROXY_TYPE_GOLD_LABEL,
  CITY_PROXY_TYPE_SILVER_LABEL,
  CITY_PROXY_TYPE_CU_LABEL,
  CITY_PROXY_TYPE_MAP
}
