const ADMIN_TYPE_SMS = 1
const ADMIN_TYPE_OMS = 2
const ADMIN_TYPE_PAMS = 3
const ADMIN_TYPE_CAMS = 4
const ADMIN_TYPE_EMS = 5
const ADMIN_TYPE_STAFF = 6

const ADMIN_TYPE_SMS_SHORT = 'sms'
const ADMIN_TYPE_OMS_SHORT = 'oms'
const ADMIN_TYPE_PAMS_SHORT = 'pams'
const ADMIN_TYPE_CAMS_SHORT = 'cams'
const ADMIN_TYPE_EMS_SHORT = 'ems'
const ADMIN_TYPE_STAFF_SHORT = 'staff'

const ADMIN_TYPE_SMS_LABEL = '超级管理后台'
const ADMIN_TYPE_OMS_LABEL = '运营商后台'
const ADMIN_TYPE_PAMS_LABEL = '省级代理后台'
const ADMIN_TYPE_CAMS_LABEL = '市级代理后台'
const ADMIN_TYPE_EMS_LABEL = '企业后台'
const ADMIN_TYPE_STAFF_LABEL = '企业员工后台'

const ADMIN_TYPE_MAP = {
  [ADMIN_TYPE_SMS]: {
    label: ADMIN_TYPE_SMS_LABEL,
    short: ADMIN_TYPE_SMS_SHORT
  },
  [ADMIN_TYPE_OMS]: {
    label: ADMIN_TYPE_OMS_LABEL,
    short: ADMIN_TYPE_OMS_SHORT
  },
  [ADMIN_TYPE_PAMS]: {
    label: ADMIN_TYPE_PAMS_LABEL,
    short: ADMIN_TYPE_PAMS_SHORT
  },
  [ADMIN_TYPE_CAMS]: {
    label: ADMIN_TYPE_CAMS_LABEL,
    short: ADMIN_TYPE_CAMS_SHORT
  },
  [ADMIN_TYPE_EMS]: {
    label: ADMIN_TYPE_EMS_LABEL,
    short: ADMIN_TYPE_EMS_SHORT
  },
  [ADMIN_TYPE_STAFF]: {
    label: ADMIN_TYPE_STAFF_LABEL,
    short: ADMIN_TYPE_STAFF_SHORT
  }
}
const ADMIN_TYPE_LIST = [{
  value: ADMIN_TYPE_SMS,
  label: ADMIN_TYPE_SMS_LABEL,
  short: ADMIN_TYPE_SMS_SHORT
}, {
  value: ADMIN_TYPE_OMS,
  label: ADMIN_TYPE_OMS_LABEL,
  short: ADMIN_TYPE_OMS_SHORT
}, {
  value: ADMIN_TYPE_PAMS,
  label: ADMIN_TYPE_PAMS_LABEL,
  short: ADMIN_TYPE_PAMS_SHORT
}, {
  value: ADMIN_TYPE_CAMS,
  label: ADMIN_TYPE_CAMS_LABEL,
  short: ADMIN_TYPE_CAMS_SHORT
}, {
  value: ADMIN_TYPE_EMS,
  label: ADMIN_TYPE_EMS_LABEL,
  short: ADMIN_TYPE_EMS_SHORT
}, {
  value: ADMIN_TYPE_STAFF,
  label: ADMIN_TYPE_STAFF_LABEL,
  short: ADMIN_TYPE_STAFF_SHORT
}]
const SYSTEM_TITLE_MAP = {
  [ADMIN_TYPE_SMS]: ADMIN_TYPE_SMS_LABEL,
  [ADMIN_TYPE_OMS]: ADMIN_TYPE_OMS_LABEL,
  [ADMIN_TYPE_PAMS]: ADMIN_TYPE_PAMS_LABEL,
  [ADMIN_TYPE_CAMS]: ADMIN_TYPE_CAMS_LABEL,
  [ADMIN_TYPE_EMS]: ADMIN_TYPE_EMS_LABEL,
  [ADMIN_TYPE_STAFF]: ADMIN_TYPE_STAFF_LABEL
}

export {
  ADMIN_TYPE_SMS,
  ADMIN_TYPE_OMS,
  ADMIN_TYPE_PAMS,
  ADMIN_TYPE_CAMS,
  ADMIN_TYPE_EMS,
  ADMIN_TYPE_STAFF,

  ADMIN_TYPE_SMS_SHORT,
  ADMIN_TYPE_OMS_SHORT,
  ADMIN_TYPE_PAMS_SHORT,
  ADMIN_TYPE_CAMS_SHORT,
  ADMIN_TYPE_EMS_SHORT,
  ADMIN_TYPE_STAFF_SHORT,

  ADMIN_TYPE_SMS_LABEL,
  ADMIN_TYPE_OMS_LABEL,
  ADMIN_TYPE_PAMS_LABEL,
  ADMIN_TYPE_CAMS_LABEL,
  ADMIN_TYPE_EMS_LABEL,
  ADMIN_TYPE_STAFF_LABEL,

  ADMIN_TYPE_MAP,
  ADMIN_TYPE_LIST,
  SYSTEM_TITLE_MAP
}
