export default entity => Object.assign({
  id: '',
  cardSlotList: [],
  cardRelateList: [],
  // cardRelateId: '',
  remarks: '',
  startTime: '',
  startType: '',
  taskName: '',
  timeTemplateId: '',
  whisperingId: '',
  whisperingTitle: '',
  validKeyNum: '',
  callNum: '',
  callTime: '',
  keyOpen: '',
  keyTemplate: '',
  messageLevelList: [],
  messageTemplate: '',
  dialect: '',
  callRate: '',
  isTransfer: '',
  transferCallNum: '',
  transferCallTime: '',
  transferKeyNum: '',
  seatList: []
}, entity)
